CREATE TABLE `Account` (
  `accountID` varchar(32) NOT NULL,
  `accountType` smallint(5) unsigned DEFAULT NULL,
  `notifyEmail` varchar(128) DEFAULT NULL,
  `speedUnits` tinyint(3) unsigned DEFAULT NULL,
  `distanceUnits` tinyint(3) unsigned DEFAULT NULL,
  `volumeUnits` tinyint(3) unsigned DEFAULT NULL,
  `pressureUnits` tinyint(3) unsigned DEFAULT NULL,
  `economyUnits` tinyint(3) unsigned DEFAULT NULL,
  `temperatureUnits` tinyint(3) unsigned DEFAULT NULL,
  `latLonFormat` tinyint(3) unsigned DEFAULT NULL,
  `geocoderMode` tinyint(3) unsigned DEFAULT NULL,
  `privateLabelName` varchar(32) DEFAULT NULL,
  `isBorderCrossing` tinyint(4) DEFAULT NULL,
  `retainedEventAge` int(10) unsigned DEFAULT NULL,
  `maximumDevices` int(11) DEFAULT NULL,
  `totalPingCount` smallint(5) unsigned DEFAULT NULL,
  `maxPingCount` smallint(5) unsigned DEFAULT NULL,
  `autoAddDevices` tinyint(4) DEFAULT NULL,
  `dcsPropertiesID` varchar(32) DEFAULT NULL,
  `expirationTime` int(10) unsigned DEFAULT NULL,
  `defaultUser` varchar(32) DEFAULT NULL,
  `password` varchar(32) DEFAULT NULL,
  `contactName` varchar(64) CHARACTER SET utf8 DEFAULT NULL,
  `contactPhone` varchar(32) DEFAULT NULL,
  `contactEmail` varchar(128) DEFAULT NULL,
  `timeZone` varchar(32) DEFAULT NULL,
  `passwdQueryTime` int(10) unsigned DEFAULT NULL,
  `lastLoginTime` int(10) unsigned DEFAULT NULL,
  `isActive` tinyint(4) DEFAULT NULL,
  `displayName` varchar(40) CHARACTER SET utf8 DEFAULT NULL,
  `description` varchar(128) CHARACTER SET utf8 DEFAULT NULL,
  `notes` text CHARACTER SET utf8,
  `lastUpdateTime` int(10) unsigned DEFAULT NULL,
  `creationTime` int(10) unsigned DEFAULT NULL,
  `smsEnabled` tinyint(4) DEFAULT NULL,
  `smsProperties` varchar(200) DEFAULT NULL,
  `emailProperties` varchar(250) DEFAULT NULL,
  `passwdChangeTime` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`accountID`),
  KEY `email` (`contactEmail`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
