CREATE TABLE `User` (
  `accountID` varchar(32) NOT NULL,
  `userID` varchar(32) NOT NULL,
  `userType` smallint(5) unsigned DEFAULT NULL,
  `roleID` varchar(32) DEFAULT NULL,
  `password` varchar(32) DEFAULT NULL,
  `gender` tinyint(3) unsigned DEFAULT NULL,
  `notifyEmail` varchar(128) DEFAULT NULL,
  `contactName` varchar(64) CHARACTER SET utf8 DEFAULT NULL,
  `contactPhone` varchar(32) DEFAULT NULL,
  `contactEmail` varchar(64) DEFAULT NULL,
  `timeZone` varchar(32) DEFAULT NULL,
  `firstLoginPageID` varchar(24) DEFAULT NULL,
  `preferredDeviceID` varchar(32) DEFAULT NULL,
  `maxAccessLevel` smallint(5) unsigned DEFAULT NULL,
  `passwdQueryTime` int(10) unsigned DEFAULT NULL,
  `lastLoginTime` int(10) unsigned DEFAULT NULL,
  `isActive` tinyint(4) DEFAULT NULL,
  `displayName` varchar(40) CHARACTER SET utf8 DEFAULT NULL,
  `description` varchar(128) CHARACTER SET utf8 DEFAULT NULL,
  `notes` text CHARACTER SET utf8,
  `lastUpdateTime` int(10) unsigned DEFAULT NULL,
  `creationTime` int(10) unsigned DEFAULT NULL,
  `passwdChangeTime` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`accountID`,`userID`),
  KEY `role` (`roleID`),
  KEY `email` (`contactEmail`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
SELECT * FROM User;